apiVersion: v1
kind: ServiceAccount
metadata:
  name: osquery-agent
  namespace: osquery-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osquery-agent
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: osquery-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osquery-agent
subjects:
- kind: ServiceAccount
  name: osquery-agent
  namespace: osquery-system
